INSERT INTO funcionario (fk_pessoa, cargo, setor) VALUES
(501, 'balconista frios e laticínios', 'VENDAS'),
(502, 'auxiliar de serviços gerais', 'LIMPEZA'),
(503, 'gerente', 'ADMINISTRATIVO'),
(504, 'repositor de estoque', 'ESTOQUE'),
(505, 'publicitário', 'ADMINISTRATIVO'),
(506, 'repositor de estoque', 'ESTOQUE'),
(507, 'balconista peixaria', 'VENDAS'),
(508, 'administrador de redes', 'TI'),
(509, 'balconista peixaria', 'VENDAS'),
(510, 'operador de caixa', 'ATENDIMENTO'),
(511, 'repositor de estoque', 'ESTOQUE'),
(512, 'operador de caixa', 'ATENDIMENTO'),
(513, 'empacotador', 'ATENDIMENTO'),
(514, 'técnico em informática', 'TI'),
(515, 'administrador de redes', 'TI'),
(516, 'auxiliar de serviços gerais', 'LIMPEZA'),
(517, 'auxiliar de serviços gerais', 'LIMPEZA'),
(518, 'repositor de estoque', 'ESTOQUE'),
(519, 'auxiliar de serviços gerais', 'LIMPEZA'),
(520, 'balconista frios e laticínios', 'VENDAS'),
(521, 'repositor de estoque', 'ESTOQUE'),
(522, 'operador de caixa', 'ATENDIMENTO'),
(523, 'empacotador', 'ATENDIMENTO'),
(524, 'repositor de estoque', 'ESTOQUE'),
(525, 'motoboy', 'ATENDIMENTO'),
(526, 'auxiliar de serviços gerais', 'LIMPEZA'),
(527, 'balconista peixaria', 'VENDAS'),
(528, 'auxiliar de serviços gerais', 'LIMPEZA'),
(529, 'auxiliar de serviços gerais', 'LIMPEZA'),
(530, 'técnico em informática', 'TI'),
(531, 'auxiliar de serviços gerais', 'LIMPEZA'),
(532, 'auxiliar de serviços gerais', 'LIMPEZA'),
(533, 'subgerente', 'ADMINISTRATIVO'),
(534, 'técnico em informática', 'TI'),
(535, 'açougue', 'VENDAS'),
(536, 'subgerente', 'ADMINISTRATIVO'),
(537, 'repositor de estoque', 'ESTOQUE'),
(538, 'administrador de redes', 'TI'),
(539, 'segurança', 'ATENDIMENTO'),
(540, 'fiscal de caixa', 'ATENDIMENTO'),
(541, 'repositor de estoque', 'ESTOQUE'),
(542, 'balconista padaria', 'VENDAS'),
(543, 'açougue', 'VENDAS'),
(544, 'publicitário', 'ADMINISTRATIVO'),
(545, 'gerente', 'ADMINISTRATIVO'),
(546, 'repositor de estoque', 'ESTOQUE'),
(547, 'subgerente', 'ADMINISTRATIVO'),
(548, 'subgerente', 'ADMINISTRATIVO'),
(549, 'auxiliar de serviços gerais', 'LIMPEZA'),
(550, 'motoboy', 'ATENDIMENTO'),
(551, 'balconista peixaria', 'VENDAS'),
(552, 'repositor de estoque', 'ESTOQUE'),
(553, 'operador de caixa', 'ATENDIMENTO'),
(554, 'técnico em suporte e manutenção', 'TI'),
(555, 'subgerente', 'ADMINISTRATIVO'),
(556, 'balconista frios e laticínios', 'VENDAS'),
(557, 'repositor de estoque', 'ESTOQUE'),
(558, 'balconista padaria', 'VENDAS'),
(559, 'balconista peixaria', 'VENDAS'),
(560, 'porteiro', 'ATENDIMENTO'),
(561, 'porteiro', 'ATENDIMENTO'),
(562, 'empacotador', 'ATENDIMENTO'),
(563, 'balconista', 'VENDAS'),
(564, 'subgerente', 'ADMINISTRATIVO'),
(565, 'repositor de estoque', 'ESTOQUE'),
(566, 'repositor de estoque', 'ESTOQUE'),
(567, 'balconista peixaria', 'VENDAS'),
(568, 'técnico em suporte e manutenção', 'TI'),
(569, 'técnico em suporte e manutenção', 'TI'),
(570, 'publicitário', 'ADMINISTRATIVO'),
(571, 'subgerente', 'ADMINISTRATIVO'),
(572, 'operador de caixa', 'ATENDIMENTO'),
(573, 'administrador de redes', 'TI'),
(574, 'fiscal de caixa', 'ATENDIMENTO'),
(575, 'técnico em recursos humanos', 'ADMINISTRATIVO'),
(576, 'empacotador', 'ATENDIMENTO'),
(577, 'repositor de estoque', 'ESTOQUE'),
(578, 'técnico em informática', 'TI'),
(579, 'repositor de estoque', 'ESTOQUE'),
(580, 'balconista peixaria', 'VENDAS'),
(581, 'técnico em recursos humanos', 'ADMINISTRATIVO'),
(582, 'balconista peixaria', 'VENDAS'),
(583, 'auxiliar de serviços gerais', 'LIMPEZA'),
(584, 'repositor de estoque', 'ESTOQUE'),
(585, 'fiscal de caixa', 'ATENDIMENTO'),
(586, 'fiscal de caixa', 'ATENDIMENTO'),
(587, 'repositor de estoque', 'ESTOQUE'),
(588, 'balconista peixaria', 'VENDAS'),
(589, 'técnico em suporte e manutenção', 'TI'),
(590, 'balconista padaria', 'VENDAS'),
(591, 'balconista frios e laticínios', 'VENDAS'),
(592, 'balconista frios e laticínios', 'VENDAS'),
(593, 'motoboy', 'ATENDIMENTO'),
(594, 'operador de caixa', 'ATENDIMENTO'),
(595, 'empacotador', 'ATENDIMENTO'),
(596, 'balconista padaria', 'VENDAS'),
(597, 'técnico em suporte e manutenção', 'TI'),
(598, 'técnico em suporte e manutenção', 'TI'),
(599, 'subgerente', 'ADMINISTRATIVO'),
(600, 'auxiliar de serviços gerais', 'LIMPEZA');